---
- name: install nginx
  package:
        name: nginx
        state: latest

- name: copy index file
  copy:
          src: index.html
          dest: /usr/share/nginx/html/index.html

- name: restart nginx
  service: 
        name: nginx
        enabled: yes
        state: restarted

